services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
      - "53:53"
    volumes:
      - ./src:/app/src
      - vscode-extensions:/run/.vscode-server/extensions
      - knot-sock:/run/knot
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - KNOT_SOCKET=/run/knot/knot.sock
    entrypoint: /app/entrypoint.sh

volumes:
  vscode-extensions:
  knot-sock: